version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "org.codehaus.groovy:*"
        # Jenkins is stuck on Groovy 2
        update-types: ["version-update:semver-major"]
